<?xml version="1.0"?>
<robot name="rover_base"
    xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find rs_description)/urdf_v2/rover_movement/utils/params.xacro"/>
    <xacro:include filename="$(find rs_description)/urdf_v2/rover_movement/utils/macros.xacro"/>
    <!-- <xacro:include filename="$(find rover_description)/urdf/sensors/_d435.urdf.xacro"/> -->

    <link name="chassis_link">
        <visual>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <mesh filename="package://rs_description/urdf_v2/rover_movement/meshes/chassis.dae"/>
            </geometry>
        </visual>
        <collision>
                <geometry>
                    <!-- <mesh filename="package://rs_description/urdf_v2/rover_movement/meshes/sway_pivot.dae"/> -->
                    <box size="${chassis_width} ${chassis_length} ${chassis_height}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>             
            </collision>
            <inertial>
                <mass value="${chassis_mass}"/>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <xacro:box_inertia mass="${chassis_mass}" width="${chassis_width}" height="${chassis_height}" />
            </inertial>
    </link>

    <xacro:swaypivot name="l" lr="${left}" />
    <xacro:swaypivot name="r" lr="${right}" />

    <joint name="l_swaypivot_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="l_swaypivot_link"/>
        <origin xyz="${1*(chassis_width/2 + sway_pivot_depth/2 + sway_pivot_gap)} 0.0 0.0" rpy="0 0 0"/>
        <axis xyz="1.0 0.0 0.0"/>
        <!-- <limit effort="1000" velocity="1000" lower="${-pi * 0.25}" upper="${pi * 0.25}"/> -->
    </joint>

    <joint name="r_swaypivot_joint" type="fixed">
        <parent link="chassis_link"/>
        <child link="r_swaypivot_link"/>
        <origin xyz="${-1*(chassis_width/2 + sway_pivot_depth/2 + sway_pivot_gap)} 0.0 0.0" rpy="0 0 0"/>
        <axis xyz="1.0 0.0 0.0"/>
        <!-- <limit effort="1000" velocity="1000" lower="${-pi * 0.25}" upper="${pi * 0.25}"/> -->
        <mimic joint="l_swaypivot_joint" multiplier="-1" offset="0"/>
    </joint>

    <xacro:leg sway="r" name="fr" fb="${front}" lr="${right}" tb="${bottom}"/>
    <xacro:leg sway="l" name="fl" fb="${front}" lr="${left}" tb="${bottom}"/>
    <xacro:leg sway="r" name="br" fb="${back}" lr="${right}" tb="${bottom}"/>
    <xacro:leg sway="l" name="bl" fb="${back}" lr="${left}" tb="${bottom}"/>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/</robotNamespace>
        </plugin> 

<!-- Copied and pasted from Gazebo plugin tutorial-->
        <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
            <updateRate>100.0</updateRate>
            <robotNamespace>/</robotNamespace>
            <leftFrontJoint>fl_wheel_joint</leftFrontJoint>
            <rightFrontJoint>fr_wheel_joint</rightFrontJoint>
            <leftRearJoint>bl_wheel_joint</leftRearJoint>
            <rightRearJoint>br_wheel_joint</rightRearJoint>
            <wheelSeparation>0.4</wheelSeparation>
            <wheelDiameter>0.215</wheelDiameter>
            <robotBaseFrame>chassis_link</robotBaseFrame>
            <torque>20</torque>
            <topicName>cmd_vel</topicName>
            <broadcastTF>false</broadcastTF>
        </plugin>
    </gazebo>

</robot>